name: Build and Deploy App to GCP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-deliver:
    uses: trevorism/actions-workflows/.github/workflows/deploy.yml@master
    secrets:
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      SIGNING_KEY: ${{secrets.SIGNING_KEY}}
    with:
      service_account: 'github-trevorism-gcloud@trevorism-gcloud.iam.gserviceaccount.com'
      workload_identity_provider: 'projects/159773244195/locations/global/workloadIdentityPools/github-trevorism-gcloud-pool/providers/trevorism-gcloud-provider'
      version: 0-3-0
      run_acceptance: true
